apiVersion: v1

kind: Service

metadata:

  name: day5-mariadb-service

spec:

  type: NodePort

  selector:

    app: day5-mariadb

  ports:

    - protocol: TCP

      port: 3306

      targetPort: 3306

