apiVersion: apps/v1

kind: Deployment

metadata:

  name: day5-wordpress-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: day5-wordpress

  template:

    metadata:

      labels:

        app: day5-wordpress

    spec:

      containers:

      - name: day5-wordpress

        image: hngtech11/wordpress:day1

        env:
          - name: WORDPRESS_DATABASE_USER

            valueFrom:

              configMapKeyRef:

                name: day5-wordpress-config

                key: MARIADB_USER

          - name: WORDPRESS_DATABASE_PASSWORD

            valueFrom:

              secretKeyRef:

                name: day5-wordpress-secrets

                key: MARIADB_PASSWORD

          - name: WORDPRESS_DATABASE_NAME

            valueFrom:

              configMapKeyRef:

                name: day5-wordpress-config

                key: MARIADB_DATABASE

          - name: ALLOW_EMPTY_PASSWORD

            valueFrom:

              configMapKeyRef:

                name: day5-wordpress-config

                key: ALLOW_EMPTY

          - name: WORDPRESS_DATABASE_HOST

            value: "day5-mariadb-service"


        ports:

          - containerPort: 8443

          - containerPort: 8080

